#define BREAK 1
#define CONTINUE 2
#define DO 3
#define ELSE 4
#define FALSE_ 5
#define FOR 6
#define FUN 7
#define IF 8
#define IN 9
#define NULL_ 10
#define RETURN 11
#define TRUE 12
#define VAL 13
#define VAR 14
#define WHEN 15
#define WHILE 16
#define IMPORT 17
#define CONST 18
#define REFER_EQUAL 19
#define REFER_NOT_EQUAL 20
#define EQUAL 21
#define NOT_EQUAL 22
#define GREATER_EQUAL 23
#define LESS_EQUAL 24
#define PLUS_EQUAL 25
#define MINUS_EQUAL 26
#define INC 27
#define DEC 28
#define AND 29
#define OR 30
#define ASSERT_NON_NULL 31
#define SAFE_CALL 32
#define ELVIS 33
#define RANGE_EXCL 34
#define RANGE_INCL 35
#define ASSIGN 36
#define PLUS 37
#define MINUS 38
#define MULT 39
#define DIV 40
#define MOD 41
#define GREATER 42
#define LESS 43
#define NOT 44
#define NULLABLE 45
#define DOT 46
#define ARRAY_ACCESS 47
#define TYPE_CAST 48
#define RIGHT_CURL 49
#define LEFT_CURL 50
#define TYPE 51
#define LPARA 52
#define RPARA 53
#define FLOAT_LITERAL 101
#define INT_LITERAL 102
#define CHAR_LITERAL 103
#define STRING_LITERAL 104
#define IDENTIFIER 257
#define FORBIDDEN 258
#define NONIDENTIFIER 259